In [10]:
import torch

In [11]:
print(torch.cuda.is_available())
device = torch.device("cuda")  # Use CUDA device if available

True


In [12]:
x = torch.arange(12, dtype=torch.float32)

print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [13]:
x = torch.arange(12, dtype=torch.float32).cuda()
print(x)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       device='cuda:0')


In [17]:
x.numel(), x.shape[0]

(12, 12)

In [18]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], device='cuda:0')

In [25]:
y = torch.zeros(2,2,2,2,2)
y

tensor([[[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]]])